/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemosRouteImport } from './routes/demos'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlayGameIdRouteImport } from './routes/play.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosRoute = DemosRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demos': typeof DemosRoute
  '/games': typeof GamesRoute
  '/learn': typeof LearnRoute
  '/settings': typeof SettingsRoute
  '/play/$gameId': typeof PlayGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demos': typeof DemosRoute
  '/games': typeof GamesRoute
  '/learn': typeof LearnRoute
  '/settings': typeof SettingsRoute
  '/play/$gameId': typeof PlayGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demos': typeof DemosRoute
  '/games': typeof GamesRoute
  '/learn': typeof LearnRoute
  '/settings': typeof SettingsRoute
  '/play/$gameId': typeof PlayGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demos'
    | '/games'
    | '/learn'
    | '/settings'
    | '/play/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demos'
    | '/games'
    | '/learn'
    | '/settings'
    | '/play/$gameId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/demos'
    | '/games'
    | '/learn'
    | '/settings'
    | '/play/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DemosRoute: typeof DemosRoute
  GamesRoute: typeof GamesRoute
  LearnRoute: typeof LearnRoute
  SettingsRoute: typeof SettingsRoute
  PlayGameIdRoute: typeof PlayGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos': {
      id: '/demos'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof DemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DemosRoute: DemosRoute,
  GamesRoute: GamesRoute,
  LearnRoute: LearnRoute,
  SettingsRoute: SettingsRoute,
  PlayGameIdRoute: PlayGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
